### ISSUE TITLE
Display the current amount of free memory to the user

### ISSUE THREAD

**Issue by faran8381** [faran8381/hello-world#3]
I try to display the current amount of free memory to the user
- [x]  determine where the code should be placed in the program  
- [x]   google search to determine how to solve the problem using java
- [x] edit the code
- [x] run & test

**Comment by faran8381** [comment]
[ ]  determine where the code should be placed in the program
[ ]  Google search to determine how to solve the problem using java
[ ]  edit the code
[ ]  run & test it

**Comment by faran8381** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
``` use Markdown to create a task list
